### ISSUE TITLE
Markbot Screenshots Issue

### ISSUE THREAD

**Issue by faithebert** [faithebert/svg-icon-sets#1]
I am getting continual loading cogs of doom when I put this into Markbot - everything else is fine just the screenshots won't load. 

@hellachella

<img width="790" alt="Screen Shot 2020-11-02 at 9 18 30 PM" src="https://user-images.githubusercontent.com/55109632/98044082-51691900-1df4-11eb-950b-2078e9ef47fd.png">

**Comment by faithebert** [comment]
@hellachella @hannahdelaney

**Comment by HannahDelaney** [comment]
Hmm, I'm not enough of a Markbot wizard to know why it's taking so long to load for you (I put it in Markbot and it loaded normally for me), but I'll have a look at your code to see if there's anything that might help with the screenshots.

**Comment by faithebert** [comment]
Okay thank you, I just checked again and they still aren't loading - totally no idea why my Markbot isn't loving this assignment in particular

**Comment by HannahDelaney** [comment]
Not sure if it will help with the loading time, but your screenshots are currently at like 80 something % off because you've got a `height: 100%;` on your `html` and your `body`. This is why when you open it in Markbot and look at the screenshots (whenever they load, ugh) your page seems to be never ending whereas the sample cuts off nicely after the content finishes. Heights are finicky selectors to play with, best to cut those for this assignment. You also have `background-repeat: no-repeat;` and `background-attachment: fixed;`, which won't let your gradient end where the content ends, so if you cut those as well, you'll be a lot closer and the gradient will align nicely to the bottom of where your content is.

Hopefully that helps a bit? I'll keep an eye for updates on how you're doing on this, big bummer when loading times on Markbot prevent you from getting things sorted faster.
